<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Framework.Abstractions\Framework.Abstractions.csproj" />
    <ProjectReference Include="..\Framework.SharedKernel\Framework.SharedKernel.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="3.12.0" />
  </ItemGroup>

</Project>
